# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 9001


spring:
  # 环境 dev|test|prod
  profiles:
    active: dev

logging:
  config: classpath:logback-spring.xml
  file:
    path: ../logs/harry-platform